steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |-
    gcloud compute ssh instance-ems --zone=asia-southeast2-a --command='/bin/sh /home/hairian/pull.sh'